### ISSUE TITLE
No longer works

### ISSUE THREAD

**Issue by Duda5** [ManoloZocco/Panopto-Video-Downloader#1]
The extension is not working, at least not on _surrey.cloud.panopto.eu_ 
I am a novice in coding, but I think it may be because they do not use `twitter:player`.
Instead, if I inspect page with video, I can find `https://www.youtube.com/iframe_api`...

Not sure whether this comment is helpful, but I would really appreciate if this "bug" could be fixed as I am not into screen-recoding full year of lectures.

**Comment by pizzo00** [comment]
Same problem but i do not find youtube link either

**Comment by ManoloZocco** [comment]
Hi, thanks for your work!
Unfortunately, some universities make changes to the original Panopto player code and I don't know how to remedy it.
I'm not a professional programmer, I just tried to adapt something to make it useful :)
So, if you know someone who can solve these problems, invite them to review the code :)

**Comment by cptmedic** [comment]
@Duda5 @pizzo00 for me to assist please provide full source code and I will take a look
