### ISSUE TITLE
not working - sept 2020

### ISSUE THREAD

**Issue by giopeco** [ManoloZocco/Panopto-Video-Downloader#3]
Ciao, grazie per il tuo codice ma purtroppo devono aver cambiato il player. Ti segnalo un paio di cose:

1. Utilizzando il segnalibro non viene restituito alcun errore, non succede semplicemente nulla.
2. Ti allego lo script che viene chiamato dalla pagina

Grazie.
[code.txt](https://github.com/ManoloZocco/Panopto-Video-Downloader/files/5214955/code.txt)

**Comment by ManoloZocco** [comment]
Ciao giopeco, grazie per il tuo lavoro.
Purtroppo alcune università apportano delle modifiche al player predefinito, in alcuni casi ne utilizzano altri, e quindi non avendo accesso ai vari sistemi utilizzati non riesco a creare rendere l'estensione compatibile per tutti.
Le mie doti di programmatore sono limitate, e le modifiche nei player delle università rischiano di tagliarmi fuori.

Nel caso tu abbia delle idee su come risolvere proponile pure :) 

A presto!

**Comment by cptmedic** [comment]
Hi, I used Google to translate this issue. Based on the rough translation I gather that nothing is happening when you try to download. To further assist, can you please provide a screenshot of your video page, and a full dump of that pages html. I see you provided pieces of it, I will need full source code as I feel like some important parts are missing.

**Comment by ManoloZocco** [comment]
> Ciao, grazie per il tuo codice ma purtroppo devono aver cambiato il player. Ti segnalo un paio di cose:
> 
> 1. Utilizzando il segnalibro non viene restituito alcun errore, non succede semplicemente nulla.
> 2. Ti allego lo script che viene chiamato dalla pagina
> 
> Grazie.
> [code.txt](https://github.com/ManoloZocco/Panopto-Video-Downloader/files/5214955/code.txt)

Ciao @giopeco, hai provato con l'ultima versione dell'estensione? Dovrebbe funzionare Ora :)
Nel caso ci sia ancora qualche problema, apri pure un altro thread :)
