### ISSUE TITLE
Not downloading, and does not raise alert on non-Panopto pages

### ISSUE THREAD

**Issue by SamuelLeeD** [ManoloZocco/Panopto-Video-Downloader#4]
I've tried the extension on a Panopto page and nothing happens when I click the button.

Looking at `payload.js`, I see that if the URL is not a Panopto URL, an alert is supposed to be shown:

`alert("Sorry, but I didn't find any videos. Are you sure the address in the search bar is with \"panopto.eu\" or \"panopto.com\" ?");`

However, even on a random non-Panopto URL, no alert shows up when clicking the button.

In Developer mode, the following error is logged when clicking the extension button:

> Unchecked runtime.lastError: Could not establish connection. Receiving end does not exist.
> **Context**
> _generated_background_page.html
> **Stack Trace**
> _generated_background_page.html:0 (anonymous function)

**Comment by ManoloZocco** [comment]
Hi, thank you for your using this extension.
Were you in a page with a video like in the screenshot on chrome web store?

**Comment by SamuelLeeD** [comment]
Nope, nothing happens even when clicking the icon on very simple pages like the Google homepage.

**Comment by tablesturn** [comment]
I am using Chromium with your plugin and I'm not sure if SamuelLeeD (and me too) are clicking on the correct button. At least in my case, I have to click the plugin button to allow site access. Maybe that's not the button which is supposed to be clicked?

Aside from that, I want to download a video from my university's own panopto instance, which is not supported(?)
At least, I can not determine how I am supposed to download the video.

**Comment by cptmedic** [comment]
@SamuelLeeD Can you give me the URL you are trying to download from. My PR so far address the issue of not alerting on non-panopto pages, but to figure out the downloading some things i may need include:
1. URL that you are downloading from to ensure it meets checks
2. If you can upload the source code of the panopto page where the video is to pastebin and share it here that would also be great.

Tag me once you get that info

**Comment by cptmedic** [comment]
![image](https://user-images.githubusercontent.com/27046411/97426601-b0ed9300-18e1-11eb-96d2-cded24328e58.png)
Above is an example of the message displaying on github when clicked

**Comment by tablesturn** [comment]
>     1. URL that you are downloading from to ensure it meets checks


I got an url I want to download from (but it does not work) but I do not want to share in public.
@cptmedic  You got an invitation to the [repo](https://github.com/tablesturn/dummy-repo) where you can see the link.

**Comment by cptmedic** [comment]
@tablesturn I am about to head to bed but I will look at your specific one later on, you want me to jsut modify the code on the repo for you

**Comment by tablesturn** [comment]
> @tablesturn I am about to head to bed but I will look at your specific one later on, you want me to jsut modify the code on the repo for you

No the repo just contains the link for you to test the extension on.

**Comment by SamuelLeeD** [comment]
> @SamuelLeeD Can you give me the URL you are trying to download from. My PR so far address the issue of not alerting on non-panopto pages, but to figure out the downloading some things i may need include:
> 
> 1. URL that you are downloading from to ensure it meets checks
> 2. If you can upload the source code of the panopto page where the video is to pastebin and share it here that would also be great.
> 
> Tag me once you get that info

Thank you for working on this.

I've cloned your fork but the issue of not alerting on non-Panopto pages is still there for me.

The URL I'm trying to download from has the following structure:

https://[UNIVERSITY NAME]lectures.cloud.panopto.eu/Panopto/Pages/Viewer.aspx?id=[VIDEO ID]

The source code (with some redactions) is [here](https://github.com/ManoloZocco/Panopto-Video-Downloader/files/5455271/panopto.txt).

**Comment by cptmedic** [comment]
@SamuelLeeD Did you clone and use check out the appropriate branch `fix`

**Comment by cptmedic** [comment]
Also can you tell me if when you search full source code if there are any .mp4 files. It seems the snippet you have given has no mention of _any_ media file.

**Comment by ManoloZocco** [comment]
@cptmedic thank you very very much for your work! I've merged everything on the master branch!
Thanks again!
